name: Stephen Feber
favicon: null
layout_spectrum: 0.04057
typography_spectrum: 0.21235
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#233e00'
    - '#fafafa'
    - '#a8b700'
    - '#768700'
  brandStrength: 0.33895372273400426
  lightness: 0.605526922037825
  saturation: 0.6614473599474877
  rhythmicContrast: 0.6251851625274867
purpose: []
