name: Stephen Feber
favicon: null
layout_spectrum: 1
typography_spectrum: 0.14268
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#2e5b9b'
    - '#bac6e1'
    - '#ffd700'
    - '#ad8c00'
  brandStrength: 1
  lightness: 0.605526922037825
  saturation: 0.6614473599474877
  rhythmicContrast: 1
purpose: []
